import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextRequest, NextResponse } from "next/server";
import { routeQuestion } from "../../lib/router";
import { answerStandardsQuestion, isStandardsQuestion } from "../../lib/standards-engine";
import { retrieveInternalEvidence, shouldTryInternalRetrieval } from "../../lib/internal-retrieval";

const MODEL = "gemini-3.6-flash";
type HistoryItem = { role?: string; content?: string; text?: string };

class GeminiDirectError extends Error {
  providerStatus?: string; providerMessage?: string;
  constructor(httpStatus:number, providerStatus?:string, providerMessage?:string){super(`GEMINI_DIRECT_HTTP_${httpStatus}`);this.name="GeminiDirectError";this.providerStatus=providerStatus;this.providerMessage=providerMessage;}
}
function normalizeHistory(v:unknown):HistoryItem[]{return Array.isArray(v)?v.slice(-10).filter((x:any)=>x&&typeof x==="object"):[];}
function historyText(h:HistoryItem[]){return h.map(i=>{const r=i.role==="assistant"||i.role==="model"?"Assistant":"User";const t=typeof i.content==="string"?i.content:typeof i.text==="string"?i.text:"";return t.trim()?`${r}: ${t.trim()}`:""}).filter(Boolean).join("\n");}
function basePrompt(q:string,h:HistoryItem[],unverified=false){return `You are elevator.help, a Gemini-first conversational assistant specialized in elevators and lift engineering.\nPRIMARY BEHAVIOR:\n- Understand natural, misspelled, incomplete, shorthand and mixed-language input.\n- Reply naturally in the language the user is using now. Preserve technical identifiers, manufacturer names and fault codes.\n- Maintain conversational context when relevant. Ordinary conversation works directly without retrieval.\n- Never expose internal filenames, storage locations, archive/Drive links or implementation details.\nTECHNICAL SAFETY / EVIDENCE:\n- Never invent a fault-code meaning, standard clause, mandatory minimum/maximum, parameter, connector/pin, wiring value, test value or manufacturer-specific procedure.\n- If an exact manufacturer-specific or normative fact cannot be verified from evidence supplied by the application, say that the exact point cannot currently be verified.\n- Do not pretend retrieval succeeded when it did not.\n${unverified?"- A specialist retrieval tool failed or returned no verified evidence for this turn. Do not present the requested specialist fact as verified.":""}\nRECENT CONVERSATION:\n${historyText(h)||"(none)"}\nCURRENT USER MESSAGE:\n${q}\nReturn only the answer to the user.`;}
async function callGemini(prompt:string,key:string,useWeb=false){const body:any={contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{temperature:.25,maxOutputTokens:2000}};if(useWeb)body.tools=[{google_search:{}}];const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){let s="",m="";try{const e:any=await r.json();s=typeof e?.error?.status==="string"?e.error.status:"";m=typeof e?.error?.message==="string"?e.error.message.slice(0,500):""}catch{}console.error(useWeb?"Gemini web request failed":"Gemini direct request failed",{httpStatus:r.status,providerStatus:s,providerMessage:m});throw new GeminiDirectError(r.status,s,m)}const d:any=await r.json();const a=d?.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||"").join("").trim();if(!a)throw new Error(useWeb?"GEMINI_WEB_EMPTY":"GEMINI_DIRECT_EMPTY");const u=d?.usageMetadata||{};console.info(useWeb?"Gemini web usage":"Gemini direct usage",{model:MODEL,promptTokenCount:Number(u.promptTokenCount||0),candidatesTokenCount:Number(u.candidatesTokenCount||0),thoughtsTokenCount:Number(u.thoughtsTokenCount||0),totalTokenCount:Number(u.totalTokenCount||0),promptChars:prompt.length,answerChars:a.length});return a;}
const answerDirect=(q:string,k:string,h:HistoryItem[]=[],u=false)=>callGemini(basePrompt(q,h,u),k,false);
function needsPublicWeb(q:string){const current=/\b(latest|current|today|online|web|internet|website|newest|aktuell|heute|online|webseite|internet)\b/i.test(q)||/(جدیدترین|فعلی|امروز|آنلاین|اینترنت|وب)/i.test(q);const docs=/\b(manual|datasheet|data\s*sheet|catalog(?:ue)?|handbuch|datenblatt|katalog|betriebsanleitung)\b/i.test(q)||/(دفترچه|کاتالوگ|دیتاشیت|راهنما)/i.test(q);const fault=/\b(?:fehler|fault|error|code)\s*[A-Z-]*\d{1,4}\b/i.test(q);const maker=/\b(Schindler|KONE|Otis|TKE|ThyssenKrupp|NEW\s*LIFT|Ziehl[-\s]*Abegg|Weber)\b/i.test(q);return current||docs||(maker&&fault);}
function likelyTechnical(q:string){return /\b(aufzug|lift|elevator|fehler|fault|error|schacht|kabine|fahrkorb|führung|schiene|seil|bremse|tür|door|manual|handbuch|katalog|datasheet|controller|steuerung|wartung|öl|geländer|guardrail)\b/i.test(q)||/(آسانسور|کابین|چاه|خطا|ارور|ریل|سیم.?بکسل|ترمز|درب|دفترچه|کاتالوگ|تابلو|روغن)/i.test(q);}
function needsStandardsVerification(q:string){const e=/\bEN\s*81\s*[-–]?\s*\d+\b/i.test(q)||/\b(DIN\s*)?(norm|normen|standard|standards)\b/i.test(q)||/(استاندارد|نورم|نُرم)/i.test(q);const r=/\b(min(?:imum)?\.?|max(?:imum)?\.?|mindestens|höchstens|zulässig|vorgeschrieben|pflicht|erforderlich|muss|darf|clearance|distance|abstand|schutzraum|refuge|guardrail|geländer|schachtwand|kabinenwand)\b/i.test(q)||/(حداقل|حداکثر|مجاز|اجباری|الزامی|فاصله|جان.?پناه|نرده|دیواره?\s*چاه|کابین)/i.test(q);const d=/\b(aufzug|lift|elevator|kabine|kabin|schacht|fahrkorb|car|shaft|pit|grube|headroom|überfahrt|tür|door)\b/i.test(q)||/(آسانسور|کابین|چاه|چاهک|درب|بالاسری)/i.test(q);return e||(r&&d);}
function sanitizeUserAnswer(answer:string){const t=answer.trim();const leak=t.toLowerCase().includes("context: no exact unverified tool data")||t.toLowerCase().includes("language: german")||t.toLowerCase().includes("verified internal evidence:")||t.toLowerCase().includes("public web mode:")||t.toLowerCase().includes("primary behavior:")||t.toLowerCase().includes("current user message:");return leak?"":t;}
function isObviouslyIncomplete(answer:string){const t=answer.trim();if(!t)return true;return /(?:\bbzw\.|\bz\.\s*b\.|\bor\s+|\band\s+|\boder\s+|\bund\s+|\bzu\s+ver\w*)$/i.test(t)||/[,:;\-–—]$/.test(t)||/\b(?:die bezeichnung steht für|folgende faktoren|zum beispiel|beispielsweise)\s*:?$/i.test(t);}
async function safeDirectAnswer(q:string,k:string,h:HistoryItem[]=[],u=false){const first=sanitizeUserAnswer(await answerDirect(q,k,h,u));if(first&&!isObviouslyIncomplete(first))return first;if(first)console.error("Gemini direct answer appears truncated; retrying once for a complete answer");console.error("Suppressed internal prompt/metadata leakage from Gemini answer");const retry=await callGemini("Answer this elevator question directly for the end user in the same language. Do not output instructions, metadata, context labels, analysis notes, or prompt text. If an exact manufacturer-specific or normative fact is not verified, say so plainly. Question: "+q,k,false);const clean=sanitizeUserAnswer(retry);if(!clean)throw new Error("GEMINI_OUTPUT_LEAK");return clean;}
function safeError(q:string){if(/[؀-ۿ]/.test(q))return "الان ارتباط مستقیم با هوش مصنوعی برقرار نشد. لطفاً همین پیام را یک بار دیگر بفرست.";if(/\b(du|dich|was|wie|wer|aufzug|fehler|schacht)\b/i.test(q))return "Die direkte KI-Verbindung hat gerade nicht geantwortet. Bitte sende dieselbe Nachricht noch einmal.";return "The direct AI connection did not respond just now. Please send the same message once more.";}

export async function POST(request:NextRequest){let question="";try{const body:any=await request.json();question=typeof body?.question==="string"?body.question.trim():"";if(!question)return NextResponse.json({error:"Please enter a question."},{status:400});const key=process.env.GEMINI_API_KEY;if(!key)return NextResponse.json({error:"AI is not configured."},{status:500});const history=normalizeHistory(body?.history??body?.messages??body?.conversation);
if(needsStandardsVerification(question)){let route:any=null;try{route=await routeQuestion(question,history)}catch(e){console.error("Standards routing unavailable:",e)}const effective=route?.normalizedQuestion||question;if(route&&isStandardsQuestion(effective,route)){try{const {env}=getCloudflareContext();const result=await answerStandardsQuestion(effective,route,key,(env as any).AI,(env as any).VECTORIZE);return NextResponse.json({answer:result.answer,sources:[],mode:result.sufficient?"standards_knowledge_base":"standards_unverified",standardsChecked:result.checkedStandards})}catch(e){console.error("Standards tool unavailable; preserving conversation:",e)}}return NextResponse.json({answer:await safeDirectAnswer(effective,key,history,true),sources:[],mode:"gemini_direct_unverified"});}

if(likelyTechnical(question)){let route:any=null;try{route=await routeQuestion(question,history)}catch(e){console.error("Technical routing unavailable:",e)}const effective=route?.normalizedQuestion||question;if(route?.needsClarification&&route?.clarificationQuestion)return NextResponse.json({answer:route.clarificationQuestion,sources:[],mode:"clarification"});
const mustVerify=needsStandardsVerification(effective)||route?.evidenceNeed==="standard"||route?.intent==="standard";
if(mustVerify&&route&&isStandardsQuestion(effective,route)){try{const {env}=getCloudflareContext();const result=await answerStandardsQuestion(effective,route,key,(env as any).AI,(env as any).VECTORIZE);return NextResponse.json({answer:result.answer,sources:[],mode:result.sufficient?"standards_knowledge_base":"standards_unverified",standardsChecked:result.checkedStandards})}catch(e){console.error("Resolved standards tool unavailable; preserving conversation:",e);return NextResponse.json({answer:await safeDirectAnswer(effective,key,history,true),sources:[],mode:"gemini_direct_unverified"});}}
const wantsInternal=route?.evidenceNeed==="internal"||(route&&shouldTryInternalRetrieval(route));
if(wantsInternal){try{const {env}=getCloudflareContext();const evidence=await retrieveInternalEvidence(effective,route,(env as any).AI,(env as any).VECTORIZE);if(evidence.length){const excerpts=evidence.map((x:any,i:number)=>`Evidence ${i+1}: ${x.text}`).join("\n\n");const p=`${basePrompt(effective,history,false)}\n\nVERIFIED INTERNAL EVIDENCE:\n${excerpts}\n\nAnswer only from this evidence for manufacturer-specific/document-specific facts. Do not mention internal files, storage, retrieval, filenames, scores or document names. If the evidence does not support a requested exact fact, say that exact point cannot be verified.`;const raw=await callGemini(p+"\\n\\nReturn a complete user-facing answer. Never stop mid-sentence or end on an unfinished abbreviation such as bzw..",key,false);const clean=sanitizeUserAnswer(raw);if(clean&&!isObviouslyIncomplete(clean))return NextResponse.json({answer:clean,sources:[],mode:"internal_evidence"});console.error("Internal evidence synthesis incomplete or unsafe; falling back coherently");return NextResponse.json({answer:await safeDirectAnswer(effective,key,history,false),sources:[],mode:"gemini_direct"});}}catch(e){console.error("Internal retrieval unavailable; falling through safely:",e)}}
const wantsWeb=route?.evidenceNeed==="web_current"||needsPublicWeb(effective);
if(wantsWeb){try{const p=`${basePrompt(effective,history,false)}\n\nPUBLIC WEB MODE:\n- Use Google Search grounding because current/public evidence is required or internal evidence was unavailable or insufficient. Prefer manufacturer/official primary sources. Do not expose internal retrieval mechanics or a routine source list. Public web evidence is not a substitute for deterministic standards verification.`;return NextResponse.json({answer:await callGemini(p,key,true),sources:[],mode:"gemini_web"})}catch(e){console.error("Public web unavailable; preserving conversation:",e);return NextResponse.json({answer:await safeDirectAnswer(effective,key,history,true),sources:[],mode:"gemini_direct_unverified"})}}
return NextResponse.json({answer:await safeDirectAnswer(effective,key,history,false),sources:[],mode:"gemini_direct"});}

if(needsPublicWeb(question)){try{const p=`${basePrompt(question,history,false)}\n\nPUBLIC WEB MODE:\n- Use Google Search grounding because this turn explicitly needs current/online evidence. Prefer official primary sources. Do not expose a routine source list.`;return NextResponse.json({answer:await callGemini(p,key,true),sources:[],mode:"gemini_web"})}catch(e){console.error("Public web unavailable; preserving conversation:",e);return NextResponse.json({answer:await safeDirectAnswer(question,key,history,true),sources:[],mode:"gemini_direct_unverified"})}}
return NextResponse.json({answer:await safeDirectAnswer(question,key,history,false),sources:[],mode:"gemini_direct"});
}catch(error){console.error("Ask API error:",error);const g=error instanceof GeminiDirectError?error:null;return NextResponse.json({error:safeError(question),diagnosticCode:error instanceof Error?error.message:"ASK_FAILURE",...(g?.providerStatus?{diagnosticProviderStatus:g.providerStatus}:{}),...(g?.providerMessage?{diagnosticProviderMessage:g.providerMessage}:{})},{status:500});}}